/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CesiumMan.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/CesiumMan.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Z_UP" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Armature" rotation={[0, 0, -Math.PI / 2]}>
            <primitive object={nodes.Skeleton_torso_joint_1} />
            <skinnedMesh name="Cesium_Man" geometry={nodes.Cesium_Man.geometry} material={materials['Cesium_Man-effect']} skeleton={nodes.Cesium_Man.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/CesiumMan.gltf')
